# Generated by Django 5.1.6 on 2025-04-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_buddy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='favoritePet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='petHappiness',
            field=models.IntegerField(default=50),
        ),
    ]
