# Generated by Django 5.1.6 on 2025-04-22 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_buddy_favoritepet_alter_buddy_pethappiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='last_session',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
